In [ ]:
#Needs the separate_steps branch on rr_nartd 
#Needs to link to the local rr_nartd repo

import pandas as pd
import pathlib
from rr.nartd.loaders.de_loader import DELoader
from rr.nartd.cleaners.base_cleaner import PandasCleaner
from rr.nartd.tokenizers.de_tokenizer import DETokenizer
import logging
logging.basicConfig(
    level=logging.INFO,  # or logging.DEBUG for more detailed output
    format='%(asctime)s - %(levelname)s - %(message)s'
)

%load_ext autoreload
%autoreload 2

In [2]:
loader = DELoader(train = True)

In [3]:
dset_original = loader.load(pathlib.Path("/mnt/g/My Drive/Python/Kantar data/Original zip files/Germany-230208_EP Coke dissag data_Jan 2021 - Dec 2022.7z"))

2025-02-08 22:56:57,010 - INFO - Loading all of data_July-Dec 2021.csv from DE data repository
2025-02-08 22:56:59,058 - INFO - Loading all of data_Jan-June 2021.csv from DE data repository
2025-02-08 22:57:01,204 - INFO - Loading all of data_Jan-June 2022.csv from DE data repository
2025-02-08 22:57:03,349 - INFO - Loading all of data_July-Oct 2022.csv from DE data repository
2025-02-08 22:57:04,824 - INFO - Loading all of data_Nov-Dec 2022.csv from DE data repository
2025-02-08 22:57:20,999 - INFO - Removing 827658 purchase_records of sales outside training supermarkets, which are PENNY, TEGUT, LIDL, REWE, GLOBUS ST. WENDEL, EDEKA EH, KAUFLAND, NETTO MARKEN-DISCOUNT

In [4]:
dset_original

,index,Customer ID,Date,Barcode,Units,Volume,Value,Price_Paid_perL,Price_Paid_perUnit,Promo_Detailed,...,Age_Primary_Shopper,KO_sales_areas,Quantity,Price,StockCode,Occasion,user_classifier,Week,Invoice,user_cluster
3,559364,18cf4731a89dc52e0ebc628116ff80a5,2021-01-01,4311596435944,2,3.00,0.38,0.126667,0.190,Regular price,...,70-74 Jahre,KO VG South,2,0.190,PL|1500|PET Not returnable|<undefined>|NARTD L...,18cf4731a89dc52e0ebc628116ff80a5|EDEKA EH|2021...,<und|1F,0,18cf4731a89dc52e0ebc628116ff80a5|EDEKA EH|0,<und|1F
5,61899,606be575c27cdf63fc938ccc6dee6e68,2021-01-01,42151555,1,1.50,0.43,0.286667,0.430,Regular price,...,45-49 Jahre,KO VG West,1,0.430,PL|1500|PET Not returnable|COLA|NARTD Regular|...,606be575c27cdf63fc938ccc6dee6e68|NETTO MARKEN-...,COLA|2,0,606be575c27cdf63fc938ccc6dee6e68|NETTO MARKEN-...,COLA|2
7,635837,553e8f201749a65152427a54c5d76bc5,2021-01-01,5760466920537,3,0.66,4.92,7.454545,1.640,Regular price,...,45-49 Jahre,KO VG South,3,1.640,STARBUCKS|220|PET Not returnable|LATTE MACCHIA...,553e8f201749a65152427a54c5d76bc5|REWE|20210101,LATT|1M,0,553e8f201749a65152427a54c5d76bc5|REWE|0,Other
11,205612,841a2e0e1040b08e9be374500d6df270,2021-01-01,4311501480045,1,0.50,0.29,0.580000,0.290,Regular price,...,50-54 Jahre,KO VG West,1,0.290,PL|500|PET Not returnable|PFIRSICH|NARTD Regul...,841a2e0e1040b08e9be374500d6df270|EDEKA EH|2021...,PFIR|3+,0,841a2e0e1040b08e9be374500d6df270|EDEKA EH|0,ORAN|3+
12,205611,841a2e0e1040b08e9be374500d6df270,2021-01-01,4007656033006,3,2.10,1.71,0.814286,0.570,Regular price,...,50-54 Jahre,KO VG West,3,0.570,SCHWARZWALD SPRUDEL|700|Glas|ORANGE|NARTD Regu...,841a2e0e1040b08e9be374500d6df270|EDEKA EH|2021...,ORAN|3+,0,841a2e0e1040b08e9be374500d6df270|EDEKA EH|0,ORAN|3+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3147812,219900,fdfe507364eabf7be23255e3dc947447,2022-12-31,4056489025085,1,1.00,1.69,1.690000,1.690,Coupon,...,50-54 Jahre,KO VG West,1,1.690,PL|1000|Carton|APFEL / ARONIAAPFEL|NARTD Regul...,fdfe507364eabf7be23255e3dc947447|LIDL|20221231,APFE|1M,104,fdfe507364eabf7be23255e3dc947447|LIDL|104,APFE|1M
3147813,176631,8b3529f0001e71670d9e546d5e4534b5,2022-12-31,4063367340697,2,2.00,1.99,0.995000,0.995,Regular price,...,50-54 Jahre,KO VG West,2,0.995,PL|1000|Carton|KIRSCH / SAUERKIRSCH|NARTD Ligh...,8b3529f0001e71670d9e546d5e4534b5|KAUFLAND|2022...,KIRS|1M,104,8b3529f0001e71670d9e546d5e4534b5|KAUFLAND|104,<und|1M
3147815,94439,2d389e062480166ebcc740b2a60d052c,2022-12-31,4009491021231,1,1.00,0.99,0.990000,0.990,Regular price,...,60-64 Jahre,KO VG West,1,0.990,VALENSINA FRUITS+|1000|PET Not returnable|APFE...,2d389e062480166ebcc740b2a60d052c|REWE|20221231,APFE|2,104,2d389e062480166ebcc740b2a60d052c|REWE|104,ITRO|2
3147816,204365,bc4a36aaf8a13167bfcd7fc0b8fb4feb,2022-12-31,5000112546477,1,1.25,0.69,0.552000,0.690,Priceoff,...,40-44 Jahre,KO VG West,1,0.690,MEZZO MIX|1250|PET Not returnable|COLA-MIX MIT...,bc4a36aaf8a13167bfcd7fc0b8fb4feb|KAUFLAND|2022...,COLA|1M,104,bc4a36aaf8a13167bfcd7fc0b8fb4feb|KAUFLAND|104,<und|1M
3147817,114968,37f1c7121f9a0da1c821103fb41b0fca,2022-12-31,4311501311998,1,1.00,1.69,1.690000,1.690,Regular price,...,25-29 Jahre,KO VG North,1,1.690,PL|1000|Carton|APFEL / ARONIAAPFEL|NARTD Regul...,37f1c7121f9a0da1c821103fb41b0fca|EDEKA EH|2022...,APFE|2,104,37f1c7121f9a0da1c821103fb41b0fca|EDEKA EH|104,COLA|2

In [10]:
cleaner = PandasCleaner(
        period_in_weeks = 6,
                  min_visits = 30,
                  min_baskets = 180,
                  min_average_spend = 0,
                  max_accepted_quantity = 12,
                  remove_singleton_baskets= False,
                  variety_quantile_bound=0.999,
                  bucket_by_store = True)

In [11]:
dset_cleaned = cleaner.clean(dset_original)

2025-02-08 23:15:17,564 - INFO - Of 2320160 purchase records, removing 0 with infinite prices and 0 missing prices.
2025-02-08 23:15:19,216 - INFO - Of 2320160 purchase records, removing 0 with zero or -ve quantity/price.

2025-02-08 23:15:22,161 - INFO - Breaking the data into 107 period(s) within retailers, of length 6 weeks each, and combining smaller retailers' periods into 'Other'
2025-02-08 23:15:22,634 - INFO - Aggregating duplicates week by week
100%|██████████| 105/105 [01:19<00:00,  1.33it/s]
2025-02-08 23:16:42,402 - INFO - After aggregation, 2000874 unique purchase records remain, down from 2320160. 7803 separate stock codes are found in the dataset. On average each is mentioned 256 times.
2025-02-08 23:16:51,789 - INFO - We observe 884518 separate bundles (baskets/invoices) costing on average $6.37 with 2 items.
2025-02-08 23:16:51,835 - INFO - The most expensive bundle costs $244.83. The biggest contains 44 items.
2025-02-08 23:16:51,864 - INFO - Of 884518 bundles, we remove the 1199 with greater variety than 16 distinct units.
2025-02-08 23:16:52,354 - INFO - Among 1978273 purchase records, 125368 have quantity > 12. Replacing these with 12.
2025-02-08 23:16:53,954 - INFO - Removing 6300 products that show up in < 180 baskets. This leaves 1499
2025-02-08 23:16:56,437 - INFO - Removing 32708 customers still with < 30 visits in the data.
2025-02-08 23:16:57,142 - INFO - Finally retaining 520363 consumption bundles.

In [12]:
dset_cleaned

,Customer ID,StockCode,Invoice,Quantity,Spend,Price,user_cluster,Period,Week,Variety,invoice_token
0,000013feca465b03def897639b5c2dcd,COCA-COLA|500|PET Not returnable|COLA|NARTD Re...,000013feca465b03def897639b5c2dcd|KAUFLAND|94,12,11.88,0.990,COLA|1F,15|KAUFLAND,95,3,0
1,000013feca465b03def897639b5c2dcd,FANTA|330|Can|ERDBEER-MISCHUNG|NARTD Regular|1...,000013feca465b03def897639b5c2dcd|KAUFLAND|94,2,1.70,0.850,COLA|1F,15|KAUFLAND,95,3,0
2,000013feca465b03def897639b5c2dcd,SURPRISE|300|PET Not returnable|MULTIVITAMIN|N...,000013feca465b03def897639b5c2dcd|KAUFLAND|94,12,14.28,1.190,COLA|1F,15|KAUFLAND,95,3,0
3,000013feca465b03def897639b5c2dcd,PL|1500|PET Not returnable|ROTE FRUECHTE|NARTD...,000013feca465b03def897639b5c2dcd|LIDL|0,12,6.84,0.570,COLA|1F,0|LIDL,1,1,1
4,000013feca465b03def897639b5c2dcd,PL|1500|PET Not returnable|APFEL / ARONIAAPFEL...,000013feca465b03def897639b5c2dcd|LIDL|10,12,9.48,0.790,COLA|1F,1|LIDL,11,2,2
...,...,...,...,...,...,...,...,...,...,...,...
1206917,fff5fac94e2727efb2dd1b204b53f7f0,PL|1000|Carton|JOHANNISBEERE/CASSIS|NARTD Regu...,fff5fac94e2727efb2dd1b204b53f7f0|LIDL|86,4,3.58,0.895,Other,14|LIDL,86,1,520358
1206918,fff5fac94e2727efb2dd1b204b53f7f0,PL|1000|Carton|JOHANNISBEERE/CASSIS|NARTD Regu...,fff5fac94e2727efb2dd1b204b53f7f0|LIDL|90,3,2.85,0.950,Other,15|LIDL,91,1,520359
1206919,fff5fac94e2727efb2dd1b204b53f7f0,PL|1000|PET Not returnable|JOHANNISBEERE/CASSI...,fff5fac94e2727efb2dd1b204b53f7f0|REWE|10,3,2.97,0.990,Other,1|REWE,10,1,520360
1206920,fff5fac94e2727efb2dd1b204b53f7f0,PL|1000|PET Not returnable|JOHANNISBEERE/CASSI...,fff5fac94e2727efb2dd1b204b53f7f0|REWE|4,6,5.94,0.990,Other,0|REWE,4,1,520361
1206921,fff5fac94e2727efb2dd1b204b53f7f0,PL|1000|PET Not returnable|JOHANNISBEERE/CASSI...,fff5fac94e2727efb2dd1b204b53f7f0|REWE|6,6,5.94,0.990,Other,1|REWE,6,1,520362

In [13]:
tokenizer = DETokenizer.create(
    stock_vocab_size=10000,
    user_vocab_size=10000,
    user_clusters=10)

NameError: name 'DETokenizer' is not defined

In [28]:
tokenizer.fit(dset)
tokenized_data = tokenizer.transform(dset)
tokenizer.set_outside_prices(tokenized_data['scans'])
#tokenized_data['scans'] = tokenized_data['scans'].to_pandas()

2025-01-21 08:41:16,756 - INFO - Clustering users into 10 groups based on Spend, Variety
2025-01-21 08:41:16,847 - INFO - Assigning to 10 clusters
2025-01-21 08:41:17,334 - INFO - Track the 1417 most frequent products, the least-viewed appears in 72 records.
2025-01-21 08:41:17,335 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,431 - INFO - Track the 163 most frequent periods, the least-viewed appears in 1 records.
2025-01-21 08:41:17,431 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,432 - INFO - Assigning to 10 clusters
2025-01-21 08:41:17,551 - INFO - Track the 1 most frequent users, the least-viewed appears in 939117 records.
2025-01-21 08:41:17,551 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,571 - INFO - Generator's mean basket size is 8.30 and mean spend is $5.12
/home/paulmainwood/projects/scratch/.venv/lib/python3.10/site-packages/polars/series/series.py:1371: RuntimeWarning: invalid value encountered in cast
  arr = arr.__array__(dtype)
2025-01-21 08:41:17,669 - INFO - Calculated outside-option prices from realized means

In [29]:
engine = "pandas"
LoaderClass = get_loader(engine)
CleanerClass = get_cleaner(engine)
TokenizerFactory = get_tokenizer(engine)

In [30]:
loader = LoaderClass()
cleaner = CleanerClass(period_in_weeks = 6,
                  min_visits = 30,
                  min_baskets = 180,
                  min_average_spend = 0,
                  max_accepted_quantity = 12,
                  remove_singleton_baskets= False,
                  variety_quantile_bound=0.999)
tokenizer = TokenizerFactory.create(
    country_code="uk",
    stock_vocab_size=10000,
    user_vocab_size=10000,
    user_clusters=10)

In [31]:

#datafr = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/France- Disaggregated data - COCA - 2020P1 A 2022P13.zip", country="fr")
#datauk = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/HHP GB DATA.zip", country="uk")
datade = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/Germany-230208_EP Coke dissag data_Jan 2021 - Dec 2022.7z", country="de")

2025-01-21 08:41:31,561 - INFO - Loading all of data_July-Dec 2021.csv from DE data repository
2025-01-21 08:41:33,712 - INFO - Loading all of data_Jan-June 2021.csv from DE data repository
2025-01-21 08:41:36,028 - INFO - Loading all of data_Jan-June 2022.csv from DE data repository
2025-01-21 08:41:38,369 - INFO - Loading all of data_July-Oct 2022.csv from DE data repository
2025-01-21 08:41:39,914 - INFO - Loading all of data_Nov-Dec 2022.csv from DE data repository
2025-01-21 08:41:55,378 - INFO - Loaded 3,147,818 purchase records from files. Removing 1,359,012 purchase records outside usual supermarkets, which are {'MUELLER', 'TENGELMANN/KAISERS', 'ROSSMANN', 'GLOBUS ST. WENDEL', 'EDEKA EH', 'FAMILA', 'REAL', 'KAUFLAND', 'NETTO MARKEN-DISCOUNT', 'LIDL'} leaving 1,788,806.

In [32]:
dset = cleaner.transform_data(datade)

2025-01-21 08:42:05,497 - INFO - Of 1788806 purchase records, removing 0 with infinite prices and 0 missing prices.
2025-01-21 08:42:05,815 - INFO - Of 1788806 purchase records, removing 0 with zero or -ve quantity/price.

2025-01-21 08:42:06,256 - INFO - To define Periods, now get, for each bundle, 'the' main store that was visited:
2025-01-21 08:42:09,624 - INFO - Breaking the data into 162 period(s) within retailers, of length 6 weeks each.
2025-01-21 08:42:09,854 - INFO - Aggregating duplicates week by week
100%|██████████| 105/105 [01:11<00:00,  1.47it/s]
2025-01-21 08:43:21,960 - INFO - After aggregation, 1542840 unique purchase records  remain, down from 1788806. 6980 separate stock codes are found in the dataset. On average each is mentioned 221 times.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/clean.py:206: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  f"${gb_i.Spend.sum().mean():2.2f} with {int(counts.mean())} items.")
2025-01-21 08:43:30,719 - INFO - We observe 828573 separate bundles (baskets/invoices) costing on average $5.27 with 1 items.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/clean.py:208: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  f"The biggest contains {int(counts.max())} items.")
2025-01-21 08:43:30,770 - INFO - The most expensive bundle costs $204.78. The biggest contains 25 items.
2025-01-21 08:43:30,796 - INFO - Of 828573 bundles, we remove the 886 with greater variety than 12 distinct units.
2025-01-21 08:43:32,317 - INFO - Removing 5563 products that show up in < 180 baskets. This leaves 1417
2025-01-21 08:43:34,524 - INFO - Removing 30725 customers still with < 30 visits in the data.
2025-01-21 08:43:36,770 - INFO - Among 939117 purchase records, 63672 have quantity > 12. Replacing these with 12.
2025-01-21 08:43:36,899 - INFO - Finally retaining 504138 consumption bundles.

In [33]:

tokenizer.fit(dset)
tokenized_data = tokenizer.transform(dset)
tokenizer.set_outside_prices(tokenized_data['scans'])
#tokenized_data['scans'] = tokenized_data['scans'].to_pandas()

2025-01-21 08:43:40,050 - INFO - Assigning Customer IDs to one of 10 clusters based on means of Spend, Variety.
2025-01-21 08:43:40,051 - INFO - Estimating from the data each observed Customer's mean Spend and Variety
2025-01-21 08:43:40,537 - INFO - Assigning each trip to one of 10 user_clusters.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/tokenize.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['user_cluster'] = user_cluster
2025-01-21 08:43:43,548 - INFO - Track the 1417 most frequent products, the least-viewed of which appears in 72 records.
2025-01-21 08:43:43,549 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,712 - INFO - Track the 163 most frequent periods, the least-viewed of which appears in 1 records.
2025-01-21 08:43:43,713 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,715 - INFO - Assigning each trip to one of 10 user_clusters.
2025-01-21 08:43:43,839 - INFO - Track the 10 most frequent users, the least-viewed of which appears in 13052 records.
2025-01-21 08:43:43,840 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,895 - INFO - Generator's mean basket size is 8.30 and mean spend is $4.45
2025-01-21 08:43:44,084 - INFO - Calculated outside-option prices from realized means, for each good and each period

In [34]:
tokenized_data['scans']

               product_token  period_token  user_token  Price  Quantity
invoice_token
0                         34            48           9  0.990        12
0                       1223            48           9  0.850         2
0                       1252            48           9  1.190        12
1                        312            19           9  0.570        12
2                         60             9           9  0.790        12
...                      ...           ...         ...    ...       ...
504133                   117             4           6  0.890         2
504134                   117             5           6  0.890         4
504135                   117            14           6  0.895         4
504136                   117            24           6  0.950         3
504137                   311           132           6  0.990         1

[939117 rows x 5 columns]

In [42]:
dg.set_data(tokenized_data)
dg.arrange_data(1024, 1)

2024-12-27 07:38:16,073 - INFO - 1024 bundles will be excluded from training and reserved as holdout.
2024-12-27 07:38:16,142 - INFO - Generating 1 signal set(s) for each of 1024 held-out bundles

In [29]:
relative_l2_penalty = 0.5/dg.n_samples
model = SimMLEModel(stock_vocab_size=len(dg.stock_vocab),
                    n_periods=dg.n_periods,
                    user_vocab_size=dg.user_vocab_size,
                    embedding_dim=args.K,
                    pooled_tastes=args.K - args.unpooled_tastes,
                    poold2d3=args.poold2d3,
                    seed=args.seed,
                    step_size=args.step_size,
                    l2_penalty=relative_l2_penalty)

NameError: name 'SimMLEModel' is not defined

In [18]:
split_data = tokenizer.token_shares.StockCode.str.split('|')

In [19]:
split_data

0       [Pepsi Max S/Fr Cola, 7920, Cans, Cola, Diet, ...
1       [Pepsi Max S/Fr Cola, 2000, Plastic Bottle, Co...
2       [Diet Coke, 7920, Cans, Cola, Diet, Carbonated...
3       [Tesco Dbl Stng NAS Squash, 15000, Plastic Bot...
4       [Coca Cola, 7920, Cans, Cola, Regular, Carbona...
                              ...
1380    [Pure Life Sprng Mnrl Wtr, 1500, Plastic Bottl...
1381    [Old Jamaica Reg, 330, Plastic Bottle, Other F...
1382    [Wait Essntl Sctt Mnrl Wtr, 2000, Plastic Bott...
1383    [Morr Svrs NAS Cola, 2000, Plastic Bottle, Col...
1384    [Waitrose Sctt M Wtr, 2000, Plastic Bottle, No...
Name: StockCode, Length: 1385, dtype: object

In [21]:
cats = pd.DataFrame(split_data.tolist(), columns=tokenizer.CATEGORIES)

In [22]:
cats

,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [24]:
token_shares = pd.concat([tokenizer.token_shares, cats], axis=1)

In [25]:
token_shares

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola|7920|Cans|Cola|Diet|Carbon...,20725,142486.739565,0.033501,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola|2000|Plastic Bottle|Cola|D...,61704,93836.382958,0.022063,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke|7920|Cans|Cola|Diet|Carbonated|Colas,11390,82349.189990,0.019362,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash|15000|Plastic Bottle...,78033,78086.030010,0.018360,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola|7920|Cans|Cola|Regular|Carbonated|Colas,7491,77949.630000,0.018327,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr|1500|Plastic Bottle|N...,306,153.209999,0.000036,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg|330|Plastic Bottle|Other Fruit...,375,142.469999,0.000033,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr|2000|Plastic Bottle|...,278,142.320001,0.000033,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola|2000|Plastic Bottle|Cola|Di...,774,131.890001,0.000031,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr|2000|Plastic Bottle|Non Fl...,154,93.950003,0.000022,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [30]:
prods = pd.DataFrame(dset.StockCode, columns=['StockCode']).merge(token_shares, on='StockCode')

In [31]:
prods

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Asda Mineral Water|6000|Plastic Bottle|Non Fla...,5736,9175.130129,0.002157,Asda Mineral Water,6000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1,Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...,1746,1938.290003,0.000456,Rubicon Exotic,1000,Cartons,Tropical/Exotic,Regular,Non Carbonated,Juice Drinks
2,Asda Fruit Juice|1000|Cartons|Orange|Regular|N...,22071,16286.719922,0.003829,Asda Fruit Juice,1000,Cartons,Orange,Regular,Non Carbonated,Pure Juices
3,Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...,8952,2930.450061,0.000689,Asda Lemonade,2000,Plastic Bottle,Lemonade Clear,Regular,Carbonated,Lemonade
4,Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...,8169,3746.890004,0.000881,Asda Zero,2000,Plastic Bottle,Orange,Diet,Carbonated,Flavoured Carbonated
...,...,...,...,...,...,...,...,...,...,...,...
2005211,Copella Pr Jc|1350|Plastic Bottle|Other Multi ...,1405,3255.129998,0.000765,Copella Pr Jc,1350,Plastic Bottle,Other Multi Fruit,Regular,Non Carbonated,Pure Juices
2005212,Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas,498,416.010007,0.000098,Coca Cola,250,Cans,Cola,Regular,Carbonated,Colas
2005213,Copella Pr Jc|900|Plastic Bottle|Apple|Regular...,507,852.599999,0.000200,Copella Pr Jc,900,Plastic Bottle,Apple,Regular,Non Carbonated,Pure Juices
2005214,Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...,2874,3049.619996,0.000717,Rbnsns NAS Frt Shoot,800,Plst Btl with Sports Cap,Other Multi Fruit,Diet,Non Carbonated,Juice Drinks
2005215,Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...,25273,29950.190281,0.007042,Tesco Pr Jc,1000,Plastic Bottle,Orange,Regular,Non Carbonated,Pure Juices

In [39]:
assert (dset.StockCode == prods.StockCode).all()

In [35]:
prods.StockCode

0          Asda Mineral Water|6000|Plastic Bottle|Non Fla...
1          Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...
2          Asda Fruit Juice|1000|Cartons|Orange|Regular|N...
3          Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...
4          Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...
                                 ...
2005211    Copella Pr Jc|1350|Plastic Bottle|Other Multi ...
2005212     Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas
2005213    Copella Pr Jc|900|Plastic Bottle|Apple|Regular...
2005214    Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...
2005215    Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...
Name: StockCode, Length: 2005216, dtype: object