In [1]:

from rube.data.clean import RawDataCleaner
import pandas as pd
from rr.nartd.first_set import import_data
from rr.nartd.store_cleaner import StoreCleaner
from rr.nartd.tokenizers import TokenizerFactory
from rube.data.real import ObservationalGenerator

import logging
logging.basicConfig(
    level=logging.INFO,  # or logging.DEBUG for more detailed output
    format='%(asctime)s - %(levelname)s - %(message)s'
)

%load_ext autoreload
%autoreload 2

In [2]:
cl = StoreCleaner(period_in_weeks = 6,
                  min_visits = 30,
                  min_baskets = 180,
                  min_average_spend = 0,
                  max_accepted_quantity = 12,
                  remove_singleton_baskets= False,
                  variety_quantile_bound=0.999)

In [4]:

#datafr = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/France- Disaggregated data - COCA - 2020P1 A 2022P13.zip", country="fr")
#datauk = import_data(n_lines = 50000000, country = "uk", zip_pathname ="/mnt/g/My Drive/Python/Kantar data/Original zip files/HHP GB DATA.zip")
dset = import_data(n_lines = 50000000, country = "de", zip_pathname = "/mnt/g/My Drive/Python/Kantar data/Original zip files/Germany-230208_EP Coke dissag data_Jan 2021 - Dec 2022.7z", train = True)

2025-01-10 08:58:20,374 - INFO - Loading all of data_July-Dec 2021.csv from DE data repository
2025-01-10 08:58:22,502 - INFO - Loading all of data_Jan-June 2021.csv from DE data repository
2025-01-10 08:58:24,699 - INFO - Loading all of data_Jan-June 2022.csv from DE data repository
2025-01-10 08:58:26,885 - INFO - Loading all of data_July-Oct 2022.csv from DE data repository
2025-01-10 08:58:28,289 - INFO - Loading all of data_Nov-Dec 2022.csv from DE data repository
2025-01-10 08:58:44,884 - INFO - Removing 827658 purchase_records of sales outside training supermarkets, which are KAUFLAND, LIDL, PENNY, GLOBUS ST. WENDEL, NETTO MARKEN-DISCOUNT, TEGUT, EDEKA EH, REWE

In [5]:
dset

,index,Customer ID,Date,Barcode,Units,Volume,Value,Price_Paid_perL,Price_Paid_perUnit,Promo_Detailed,...,Age_Primary_Shopper,KO_sales_areas,Quantity,Price,StockCode,Occasion,user_classifier,Week,Invoice,user_cluster
3,559364,18cf4731a89dc52e0ebc628116ff80a5,2021-01-01,4311596435944,2,3.00,0.38,0.126667,0.190,Regular price,...,70-74 Jahre,KO VG South,2,0.190,PL GUT&GUENSTIG|1500|PET Not returnable|<undef...,18cf4731a89dc52e0ebc628116ff80a5|EDEKA EH|2021...,<und|1F|65+,0,18cf4731a89dc52e0ebc628116ff80a5|EDEKA EH|0,<und|1F|65+
5,61899,606be575c27cdf63fc938ccc6dee6e68,2021-01-01,42151555,1,1.50,0.43,0.286667,0.430,Regular price,...,45-49 Jahre,KO VG West,1,0.430,PL STARDRINK|1500|PET Not returnable|COLA|NART...,606be575c27cdf63fc938ccc6dee6e68|NETTO MARKEN-...,COLA|2|30-65,0,606be575c27cdf63fc938ccc6dee6e68|NETTO MARKEN-...,COLA|2|30-65
7,635837,553e8f201749a65152427a54c5d76bc5,2021-01-01,5760466920537,3,0.66,4.92,7.454545,1.640,Regular price,...,45-49 Jahre,KO VG South,3,1.640,STARBUCKS|220|PET Not returnable|LATTE MACCHIA...,553e8f201749a65152427a54c5d76bc5|REWE|20210101,LATT|1M|30-65,0,553e8f201749a65152427a54c5d76bc5|REWE|0,Other
11,205612,841a2e0e1040b08e9be374500d6df270,2021-01-01,4311501480045,1,0.50,0.29,0.580000,0.290,Regular price,...,50-54 Jahre,KO VG West,1,0.290,PL GUT&GUENSTIG|500|PET Not returnable|PFIRSIC...,841a2e0e1040b08e9be374500d6df270|EDEKA EH|2021...,PFIR|3+|30-65,0,841a2e0e1040b08e9be374500d6df270|EDEKA EH|0,ORAN|3+|30-65
12,205611,841a2e0e1040b08e9be374500d6df270,2021-01-01,4007656033006,3,2.10,1.71,0.814286,0.570,Regular price,...,50-54 Jahre,KO VG West,3,0.570,SCHWARZWALD SPRUDEL|700|Glas|ORANGE|NARTD Regu...,841a2e0e1040b08e9be374500d6df270|EDEKA EH|2021...,ORAN|3+|30-65,0,841a2e0e1040b08e9be374500d6df270|EDEKA EH|0,ORAN|3+|30-65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3147812,219900,fdfe507364eabf7be23255e3dc947447,2022-12-31,4056489025085,1,1.00,1.69,1.690000,1.690,Coupon,...,50-54 Jahre,KO VG West,1,1.690,PL SOLEVITA|1000|Carton|APFEL / ARONIAAPFEL|NA...,fdfe507364eabf7be23255e3dc947447|LIDL|20221231,APFE|1M|30-65,104,fdfe507364eabf7be23255e3dc947447|LIDL|104,APFE|1M|30-65
3147813,176631,8b3529f0001e71670d9e546d5e4534b5,2022-12-31,4063367340697,2,2.00,1.99,0.995000,0.995,Regular price,...,50-54 Jahre,KO VG West,2,0.995,PL K-CLASSIC|1000|Carton|KIRSCH / SAUERKIRSCH|...,8b3529f0001e71670d9e546d5e4534b5|KAUFLAND|2022...,KIRS|1M|30-65,104,8b3529f0001e71670d9e546d5e4534b5|KAUFLAND|104,<und|1M|30-65
3147815,94439,2d389e062480166ebcc740b2a60d052c,2022-12-31,4009491021231,1,1.00,0.99,0.990000,0.990,Regular price,...,60-64 Jahre,KO VG West,1,0.990,VALENSINA FRUITS+|1000|PET Not returnable|APFE...,2d389e062480166ebcc740b2a60d052c|REWE|20221231,APFE|2|65+,104,2d389e062480166ebcc740b2a60d052c|REWE|104,ITRO|2|65+
3147816,204365,bc4a36aaf8a13167bfcd7fc0b8fb4feb,2022-12-31,5000112546477,1,1.25,0.69,0.552000,0.690,Priceoff,...,40-44 Jahre,KO VG West,1,0.690,MEZZO MIX|1250|PET Not returnable|COLA-MIX MIT...,bc4a36aaf8a13167bfcd7fc0b8fb4feb|KAUFLAND|2022...,COLA|1M|30-65,104,bc4a36aaf8a13167bfcd7fc0b8fb4feb|KAUFLAND|104,<und|1M|30-65
3147817,114968,37f1c7121f9a0da1c821103fb41b0fca,2022-12-31,4311501311998,1,1.00,1.69,1.690000,1.690,Regular price,...,25-29 Jahre,KO VG North,1,1.690,PL EDEKA BIO|1000|Carton|APFEL / ARONIAAPFEL|N...,37f1c7121f9a0da1c821103fb41b0fca|EDEKA EH|2022...,APFE|2|<30,104,37f1c7121f9a0da1c821103fb41b0fca|EDEKA EH|104,COLA|2|<30

In [11]:
top_products = (dset.groupby('Barcode')
                 .apply(lambda x: pd.Series({
                     'Total_Quantity': x['Quantity'].sum(),
                     'Total_Spend': (x['Quantity'] * x['Price']).sum(),
                     'StockCode': x['StockCode'].iloc[0],
                     'NARTD_Sub_segments': x['NARTD_Sub_segments'].iloc[0],
                 }))
                 .sort_values('Total_Spend', ascending=False)
                 .reset_index())

/tmp/ipykernel_11855/710010099.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

In [12]:
top_products

,Barcode,Total_Quantity,Total_Spend,StockCode,NARTD_Sub_segments
0,5449000017888,107997,88847.15380,COCA-COLA|1000|PET Returnable|COLA|NARTD Regul...,Cola
1,5000112546415,85003,82436.39046,COCA-COLA|1250|PET Not returnable|COLA|NARTD R...,Cola
2,5000112576009,49312,47031.44307,COCA-COLA ZERO|1250|PET Not returnable|COLA|NA...,Cola
3,5449000105394,49207,45411.62308,COCA-COLA|1250|PET Not returnable|COLA|NARTD R...,Cola
4,5449000134264,48505,40189.65296,COCA-COLA ZERO|1000|PET Returnable|COLA|NARTD ...,Cola
...,...,...,...,...,...
11507,XMV0049904015,1,0.25000,RESTLICHE MARKEN|250|PET Not returnable|ZZ OHN...,Sport drinks
11508,4260412069996,1,0.19833,EIZBACH|330|Glas|KRAEUTER|NARTD Regular|1|Lemo...,Lemonade other Fruit Flavor
11509,XMV0049748114,1,0.19000,RESTLICHE MARKEN|250|Can|COLA|NARTD Light / Ze...,Cola
11510,4042600380782,1,0.19000,CHRISTINEN BIO|330|PET Not returnable|<undefin...,Water Sparkling (Classic / Medium)
11511,4005012461708,1,0.14500,AQUA FRISCH|500|PET Not returnable|<undefined>...,Water Sparkling (Classic / Medium)

In [38]:
dset.Retailer.unique()

array(['ALDI', 'EDEKA EH', 'NETTO MARKEN-DISCOUNT', 'REWE', 'LIDL',
       'KAUFLAND', 'NORMA', 'PENNY', 'GLOBUS ST. WENDEL', 'MARKTKAUF',
       'ROSSMANN', 'REAL', 'TEGUT', 'FAMILA', 'DM', 'HIT', 'MUELLER',
       'TENGELMANN/KAISERS'], dtype=object)

In [1]:
dset = cl.transform_data(dset)

NameError: name 'cl' is not defined

In [21]:
dset_main == dset_branch

NameError: name 'dset_main' is not defined

In [32]:
top_products = (dset.groupby('StockCode')
                 .apply(lambda x: pd.Series({
                     'Total_Quantity': x['Quantity'].sum(),
                     'Price': x['Price'].iloc[0],  # Take first price
                     'Total_Spend': (x['Quantity'] * x['Price']).sum()
                 }))
                 .sort_values('Total_Spend', ascending=False)
                 .reset_index())

/tmp/ipykernel_1604/1319778962.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

In [33]:
top_products

,StockCode,Total_Quantity,Price,Total_Spend
0,COCA-COLA|1000ml|PET Returnable|COLA|NARTD Reg...,31600.0,1.090000,26570.72212
1,PL JA|1500ml|PET Not returnable|<undefined>|NA...,107760.0,0.190000,21900.13876
2,COCA-COLA ZERO|1000ml|PET Returnable|COLA|NART...,18475.0,0.730833,15590.51542
3,GEROLSTEINER|1000ml|PET Returnable|<undefined>...,27857.0,0.446170,13705.94103
4,COCA-COLA|1500ml|PET Not returnable|COLA|NARTD...,11792.0,1.350000,13634.52496
...,...,...,...,...
4903,FLOETZINGER|500ml|Glas|ZITRONE / LEMON|NARTD R...,1.0,0.288000,0.28800
4904,PRIVATE LABEL|1000ml|PET Not returnable|COLA|N...,1.0,0.250000,0.25000
4905,EICHENTALER|700ml|Glas|<undefined>|NARTD Light...,1.0,0.220000,0.22000
4906,THE LINK|330ml|Can|ORANGE|NARTD Regular|Still|...,1.0,0.201300,0.20130
4907,CHRISTINEN BIO|330ml|PET Not returnable|<undef...,1.0,0.190000,0.19000

In [40]:
tokenizer.fit(dset)

2024-12-27 07:37:46,837 - INFO - Clustering users into 10 groups based on Spend, Variety
2024-12-27 07:37:46,988 - INFO - Assigning to 10 clusters

In [41]:
tokenized_data = tokenizer.transform(dset)
tokenizer.set_outside_prices(tokenized_data['scans'])
tokenizer.save(fit_dir / 'tokenizer')
tokenizer.to_pandas()
tokenized_data['scans'] = tokenized_data['scans'].to_pandas()

2024-12-27 07:37:52,780 - INFO - Track the 1417 most frequent products, the least-viewed appears in 72 records.
2024-12-27 07:37:52,781 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2024-12-27 07:37:52,870 - INFO - Track the 163 most frequent periods, the least-viewed appears in 1 records.
2024-12-27 07:37:52,871 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2024-12-27 07:37:52,872 - INFO - Assigning to 10 clusters
2024-12-27 07:37:52,995 - INFO - Track the 1 most frequent users, the least-viewed appears in 939117 records.
2024-12-27 07:37:52,996 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2024-12-27 07:37:53,028 - INFO - Generator's mean basket size is 8.30 and mean spend is $5.12
/home/paulmainwood/projects/scratch/.venv/lib/python3.10/site-packages/polars/series/series.py:1371: RuntimeWarning: invalid value encountered in cast
  arr = arr.__array__(dtype)
2024-12-27 07:37:53,126 - INFO - Calculated outside-option prices from realized means

In [27]:
dg = ObservationalGenerator(1024, 31, tokenizer, seed=42, signal_function=None)

2024-12-23 21:57:12,101 - INFO - Shuffling the data at start of epoch, before cycling through without replacement
2024-12-23 21:57:12,103 - WARNING - The Signal Sets' -ve items are generated with replacement. While this is a speedup, it may fail our assumptions for consistency.

In [42]:
dg.set_data(tokenized_data)
dg.arrange_data(1024, 1)

2024-12-27 07:38:16,073 - INFO - 1024 bundles will be excluded from training and reserved as holdout.
2024-12-27 07:38:16,142 - INFO - Generating 1 signal set(s) for each of 1024 held-out bundles

In [29]:
relative_l2_penalty = 0.5/dg.n_samples
model = SimMLEModel(stock_vocab_size=len(dg.stock_vocab),
                    n_periods=dg.n_periods,
                    user_vocab_size=dg.user_vocab_size,
                    embedding_dim=args.K,
                    pooled_tastes=args.K - args.unpooled_tastes,
                    poold2d3=args.poold2d3,
                    seed=args.seed,
                    step_size=args.step_size,
                    l2_penalty=relative_l2_penalty)

NameError: name 'SimMLEModel' is not defined

In [18]:
split_data = tokenizer.token_shares.StockCode.str.split('|')

In [19]:
split_data

0       [Pepsi Max S/Fr Cola, 7920, Cans, Cola, Diet, ...
1       [Pepsi Max S/Fr Cola, 2000, Plastic Bottle, Co...
2       [Diet Coke, 7920, Cans, Cola, Diet, Carbonated...
3       [Tesco Dbl Stng NAS Squash, 15000, Plastic Bot...
4       [Coca Cola, 7920, Cans, Cola, Regular, Carbona...
                              ...
1380    [Pure Life Sprng Mnrl Wtr, 1500, Plastic Bottl...
1381    [Old Jamaica Reg, 330, Plastic Bottle, Other F...
1382    [Wait Essntl Sctt Mnrl Wtr, 2000, Plastic Bott...
1383    [Morr Svrs NAS Cola, 2000, Plastic Bottle, Col...
1384    [Waitrose Sctt M Wtr, 2000, Plastic Bottle, No...
Name: StockCode, Length: 1385, dtype: object

In [21]:
cats = pd.DataFrame(split_data.tolist(), columns=tokenizer.CATEGORIES)

In [22]:
cats

,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [24]:
token_shares = pd.concat([tokenizer.token_shares, cats], axis=1)

In [25]:
token_shares

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola|7920|Cans|Cola|Diet|Carbon...,20725,142486.739565,0.033501,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola|2000|Plastic Bottle|Cola|D...,61704,93836.382958,0.022063,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke|7920|Cans|Cola|Diet|Carbonated|Colas,11390,82349.189990,0.019362,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash|15000|Plastic Bottle...,78033,78086.030010,0.018360,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola|7920|Cans|Cola|Regular|Carbonated|Colas,7491,77949.630000,0.018327,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr|1500|Plastic Bottle|N...,306,153.209999,0.000036,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg|330|Plastic Bottle|Other Fruit...,375,142.469999,0.000033,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr|2000|Plastic Bottle|...,278,142.320001,0.000033,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola|2000|Plastic Bottle|Cola|Di...,774,131.890001,0.000031,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr|2000|Plastic Bottle|Non Fl...,154,93.950003,0.000022,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [30]:
prods = pd.DataFrame(dset.StockCode, columns=['StockCode']).merge(token_shares, on='StockCode')

In [31]:
prods

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Asda Mineral Water|6000|Plastic Bottle|Non Fla...,5736,9175.130129,0.002157,Asda Mineral Water,6000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1,Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...,1746,1938.290003,0.000456,Rubicon Exotic,1000,Cartons,Tropical/Exotic,Regular,Non Carbonated,Juice Drinks
2,Asda Fruit Juice|1000|Cartons|Orange|Regular|N...,22071,16286.719922,0.003829,Asda Fruit Juice,1000,Cartons,Orange,Regular,Non Carbonated,Pure Juices
3,Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...,8952,2930.450061,0.000689,Asda Lemonade,2000,Plastic Bottle,Lemonade Clear,Regular,Carbonated,Lemonade
4,Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...,8169,3746.890004,0.000881,Asda Zero,2000,Plastic Bottle,Orange,Diet,Carbonated,Flavoured Carbonated
...,...,...,...,...,...,...,...,...,...,...,...
2005211,Copella Pr Jc|1350|Plastic Bottle|Other Multi ...,1405,3255.129998,0.000765,Copella Pr Jc,1350,Plastic Bottle,Other Multi Fruit,Regular,Non Carbonated,Pure Juices
2005212,Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas,498,416.010007,0.000098,Coca Cola,250,Cans,Cola,Regular,Carbonated,Colas
2005213,Copella Pr Jc|900|Plastic Bottle|Apple|Regular...,507,852.599999,0.000200,Copella Pr Jc,900,Plastic Bottle,Apple,Regular,Non Carbonated,Pure Juices
2005214,Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...,2874,3049.619996,0.000717,Rbnsns NAS Frt Shoot,800,Plst Btl with Sports Cap,Other Multi Fruit,Diet,Non Carbonated,Juice Drinks
2005215,Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...,25273,29950.190281,0.007042,Tesco Pr Jc,1000,Plastic Bottle,Orange,Regular,Non Carbonated,Pure Juices

In [39]:
assert (dset.StockCode == prods.StockCode).all()

In [35]:
prods.StockCode

0          Asda Mineral Water|6000|Plastic Bottle|Non Fla...
1          Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...
2          Asda Fruit Juice|1000|Cartons|Orange|Regular|N...
3          Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...
4          Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...
                                 ...
2005211    Copella Pr Jc|1350|Plastic Bottle|Other Multi ...
2005212     Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas
2005213    Copella Pr Jc|900|Plastic Bottle|Apple|Regular...
2005214    Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...
2005215    Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...
Name: StockCode, Length: 2005216, dtype: object