In [1]:

#Needs dual_dataloader branch on rr_nartd   

from rube.data.clean import RawDataCleaner
import polars as pl
import pandas as pd
from rr.nartd.loader import get_loader
from rr.nartd.cleaner import get_cleaner
from rr.nartd.tokenizer import get_tokenizer
from rube.data.real import ObservationalGenerator

import logging
logging.basicConfig(
    level=logging.INFO,  # or logging.DEBUG for more detailed output
    format='%(asctime)s - %(levelname)s - %(message)s'
)

%load_ext autoreload
%autoreload 2

In [24]:
engine = "polars"
LoaderClass = get_loader(engine)
CleanerClass = get_cleaner(engine)
TokenizerFactory = get_tokenizer(engine)

In [25]:
loader = LoaderClass()
cleaner = CleanerClass(period_in_weeks = 6,
                  min_visits = 30,
                  min_baskets = 180,
                  min_average_spend = 0,
                  max_accepted_quantity = 12,
                  remove_singleton_baskets= False,
                  variety_quantile_bound=0.999)
tokenizer = TokenizerFactory.create(
    country_code="uk",
    stock_vocab_size=10000,
    user_vocab_size=10000,
    user_clusters=10)

In [26]:

#datafr = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/France- Disaggregated data - COCA - 2020P1 A 2022P13.zip", country="fr")
#datauk = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/HHP GB DATA.zip", country="uk")
datade = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/Germany-230208_EP Coke dissag data_Jan 2021 - Dec 2022.7z", country="de")

2025-01-21 08:41:11,251 - INFO - Loading all of data_July-Dec 2021.csv from DE data repository
2025-01-21 08:41:11,406 - INFO - Loading all of data_Jan-June 2021.csv from DE data repository
2025-01-21 08:41:11,576 - INFO - Loading all of data_Jan-June 2022.csv from DE data repository
2025-01-21 08:41:11,749 - INFO - Loading all of data_July-Oct 2022.csv from DE data repository
2025-01-21 08:41:11,887 - INFO - Loading all of data_Nov-Dec 2022.csv from DE data repository
2025-01-21 08:41:13,577 - INFO - Loaded 3,147,818 purchase records from files. Removing 1,359,012 purchase records outside usual supermarkets, which are {'MUELLER', 'TENGELMANN/KAISERS', 'ROSSMANN', 'GLOBUS ST. WENDEL', 'EDEKA EH', 'FAMILA', 'REAL', 'KAUFLAND', 'NETTO MARKEN-DISCOUNT', 'LIDL'} leaving 1,788,806.

In [27]:
dset = cleaner.transform_data(datade)

2025-01-21 08:41:14,043 - INFO - Of 1,788,806 purchase records, removing 0 with infinite or missing prices

2025-01-21 08:41:14,056 - INFO - Of 1,788,806 purchase records, removing 0 with zero or -ve quantity/price.
2025-01-21 08:41:14,057 - INFO - To define Periods, now get, for each bundle, 'the' main store that was visited:
2025-01-21 08:41:14,202 - INFO - Breaking the data into 162 period(s) within retailers, of length 6 weeks each.
2025-01-21 08:41:14,948 - INFO - After aggregation, 1,542,840 unique purchase records remain, down from 1,788,806. 6,980 separate stock codes are found.
2025-01-21 08:41:15,280 - INFO - We observe 828,573 separate bundles costing on average $5.27 with 1 items.
2025-01-21 08:41:15,281 - INFO - The most expensive bundle costs $204.78. The biggest contains 25 items.
2025-01-21 08:41:15,284 - INFO - Of 828,573 bundles, we remove those with greater variety than 12 distinct units.
2025-01-21 08:41:15,309 - INFO - Among 1,530,716 purchase records, 102,890 have quantity > 12. Replacing these with 12.
2025-01-21 08:41:15,605 - INFO - Removing 5,563 products that show up in < 180 baskets.
2025-01-21 08:41:16,031 - INFO - Removing 30725 customers who did not meet minimum visits/spend criteria.
2025-01-21 08:41:16,368 - INFO - Finally retaining 504,138 consumption bundles.

In [28]:
tokenizer.fit(dset)
tokenized_data = tokenizer.transform(dset)
tokenizer.set_outside_prices(tokenized_data['scans'])
#tokenized_data['scans'] = tokenized_data['scans'].to_pandas()

2025-01-21 08:41:16,756 - INFO - Clustering users into 10 groups based on Spend, Variety
2025-01-21 08:41:16,847 - INFO - Assigning to 10 clusters
2025-01-21 08:41:17,334 - INFO - Track the 1417 most frequent products, the least-viewed appears in 72 records.
2025-01-21 08:41:17,335 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,431 - INFO - Track the 163 most frequent periods, the least-viewed appears in 1 records.
2025-01-21 08:41:17,431 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,432 - INFO - Assigning to 10 clusters
2025-01-21 08:41:17,551 - INFO - Track the 1 most frequent users, the least-viewed appears in 939117 records.
2025-01-21 08:41:17,551 - INFO - Vocab size larger than unique units, encoded everything, no UNK.
2025-01-21 08:41:17,571 - INFO - Generator's mean basket size is 8.30 and mean spend is $5.12
/home/paulmainwood/projects/scratch/.venv/lib/python3.10/site-packages/polars/series/series.py:1371: RuntimeWarning: invalid value encountered in cast
  arr = arr.__array__(dtype)
2025-01-21 08:41:17,669 - INFO - Calculated outside-option prices from realized means

In [29]:
engine = "pandas"
LoaderClass = get_loader(engine)
CleanerClass = get_cleaner(engine)
TokenizerFactory = get_tokenizer(engine)

In [30]:
loader = LoaderClass()
cleaner = CleanerClass(period_in_weeks = 6,
                  min_visits = 30,
                  min_baskets = 180,
                  min_average_spend = 0,
                  max_accepted_quantity = 12,
                  remove_singleton_baskets= False,
                  variety_quantile_bound=0.999)
tokenizer = TokenizerFactory.create(
    country_code="uk",
    stock_vocab_size=10000,
    user_vocab_size=10000,
    user_clusters=10)

In [31]:

#datafr = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/France- Disaggregated data - COCA - 2020P1 A 2022P13.zip", country="fr")
#datauk = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/HHP GB DATA.zip", country="uk")
datade = loader.load_and_process(file_path="/mnt/g/My Drive/Python/Kantar data/Original zip files/Germany-230208_EP Coke dissag data_Jan 2021 - Dec 2022.7z", country="de")

2025-01-21 08:41:31,561 - INFO - Loading all of data_July-Dec 2021.csv from DE data repository
2025-01-21 08:41:33,712 - INFO - Loading all of data_Jan-June 2021.csv from DE data repository
2025-01-21 08:41:36,028 - INFO - Loading all of data_Jan-June 2022.csv from DE data repository
2025-01-21 08:41:38,369 - INFO - Loading all of data_July-Oct 2022.csv from DE data repository
2025-01-21 08:41:39,914 - INFO - Loading all of data_Nov-Dec 2022.csv from DE data repository
2025-01-21 08:41:55,378 - INFO - Loaded 3,147,818 purchase records from files. Removing 1,359,012 purchase records outside usual supermarkets, which are {'MUELLER', 'TENGELMANN/KAISERS', 'ROSSMANN', 'GLOBUS ST. WENDEL', 'EDEKA EH', 'FAMILA', 'REAL', 'KAUFLAND', 'NETTO MARKEN-DISCOUNT', 'LIDL'} leaving 1,788,806.

In [32]:
dset = cleaner.transform_data(datade)

2025-01-21 08:42:05,497 - INFO - Of 1788806 purchase records, removing 0 with infinite prices and 0 missing prices.
2025-01-21 08:42:05,815 - INFO - Of 1788806 purchase records, removing 0 with zero or -ve quantity/price.

2025-01-21 08:42:06,256 - INFO - To define Periods, now get, for each bundle, 'the' main store that was visited:
2025-01-21 08:42:09,624 - INFO - Breaking the data into 162 period(s) within retailers, of length 6 weeks each.
2025-01-21 08:42:09,854 - INFO - Aggregating duplicates week by week
100%|██████████| 105/105 [01:11<00:00,  1.47it/s]
2025-01-21 08:43:21,960 - INFO - After aggregation, 1542840 unique purchase records  remain, down from 1788806. 6980 separate stock codes are found in the dataset. On average each is mentioned 221 times.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/clean.py:206: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  f"${gb_i.Spend.sum().mean():2.2f} with {int(counts.mean())} items.")
2025-01-21 08:43:30,719 - INFO - We observe 828573 separate bundles (baskets/invoices) costing on average $5.27 with 1 items.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/clean.py:208: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  f"The biggest contains {int(counts.max())} items.")
2025-01-21 08:43:30,770 - INFO - The most expensive bundle costs $204.78. The biggest contains 25 items.
2025-01-21 08:43:30,796 - INFO - Of 828573 bundles, we remove the 886 with greater variety than 12 distinct units.
2025-01-21 08:43:32,317 - INFO - Removing 5563 products that show up in < 180 baskets. This leaves 1417
2025-01-21 08:43:34,524 - INFO - Removing 30725 customers still with < 30 visits in the data.
2025-01-21 08:43:36,770 - INFO - Among 939117 purchase records, 63672 have quantity > 12. Replacing these with 12.
2025-01-21 08:43:36,899 - INFO - Finally retaining 504138 consumption bundles.

In [33]:

tokenizer.fit(dset)
tokenized_data = tokenizer.transform(dset)
tokenizer.set_outside_prices(tokenized_data['scans'])
#tokenized_data['scans'] = tokenized_data['scans'].to_pandas()

2025-01-21 08:43:40,050 - INFO - Assigning Customer IDs to one of 10 clusters based on means of Spend, Variety.
2025-01-21 08:43:40,051 - INFO - Estimating from the data each observed Customer's mean Spend and Variety
2025-01-21 08:43:40,537 - INFO - Assigning each trip to one of 10 user_clusters.
/home/paulmainwood/projects/RUBE_proprietary/lib/rube/data/tokenize.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['user_cluster'] = user_cluster
2025-01-21 08:43:43,548 - INFO - Track the 1417 most frequent products, the least-viewed of which appears in 72 records.
2025-01-21 08:43:43,549 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,712 - INFO - Track the 163 most frequent periods, the least-viewed of which appears in 1 records.
2025-01-21 08:43:43,713 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,715 - INFO - Assigning each trip to one of 10 user_clusters.
2025-01-21 08:43:43,839 - INFO - Track the 10 most frequent users, the least-viewed of which appears in 13052 records.
2025-01-21 08:43:43,840 - INFO - Since vocab_size was larger than the observed number of unique units, we have encoded every unit, and there is no UNK.
2025-01-21 08:43:43,895 - INFO - Generator's mean basket size is 8.30 and mean spend is $4.45
2025-01-21 08:43:44,084 - INFO - Calculated outside-option prices from realized means, for each good and each period

In [34]:
tokenized_data['scans']

               product_token  period_token  user_token  Price  Quantity
invoice_token
0                         34            48           9  0.990        12
0                       1223            48           9  0.850         2
0                       1252            48           9  1.190        12
1                        312            19           9  0.570        12
2                         60             9           9  0.790        12
...                      ...           ...         ...    ...       ...
504133                   117             4           6  0.890         2
504134                   117             5           6  0.890         4
504135                   117            14           6  0.895         4
504136                   117            24           6  0.950         3
504137                   311           132           6  0.990         1

[939117 rows x 5 columns]

In [42]:
dg.set_data(tokenized_data)
dg.arrange_data(1024, 1)

2024-12-27 07:38:16,073 - INFO - 1024 bundles will be excluded from training and reserved as holdout.
2024-12-27 07:38:16,142 - INFO - Generating 1 signal set(s) for each of 1024 held-out bundles

In [29]:
relative_l2_penalty = 0.5/dg.n_samples
model = SimMLEModel(stock_vocab_size=len(dg.stock_vocab),
                    n_periods=dg.n_periods,
                    user_vocab_size=dg.user_vocab_size,
                    embedding_dim=args.K,
                    pooled_tastes=args.K - args.unpooled_tastes,
                    poold2d3=args.poold2d3,
                    seed=args.seed,
                    step_size=args.step_size,
                    l2_penalty=relative_l2_penalty)

NameError: name 'SimMLEModel' is not defined

In [18]:
split_data = tokenizer.token_shares.StockCode.str.split('|')

In [19]:
split_data

0       [Pepsi Max S/Fr Cola, 7920, Cans, Cola, Diet, ...
1       [Pepsi Max S/Fr Cola, 2000, Plastic Bottle, Co...
2       [Diet Coke, 7920, Cans, Cola, Diet, Carbonated...
3       [Tesco Dbl Stng NAS Squash, 15000, Plastic Bot...
4       [Coca Cola, 7920, Cans, Cola, Regular, Carbona...
                              ...
1380    [Pure Life Sprng Mnrl Wtr, 1500, Plastic Bottl...
1381    [Old Jamaica Reg, 330, Plastic Bottle, Other F...
1382    [Wait Essntl Sctt Mnrl Wtr, 2000, Plastic Bott...
1383    [Morr Svrs NAS Cola, 2000, Plastic Bottle, Col...
1384    [Waitrose Sctt M Wtr, 2000, Plastic Bottle, No...
Name: StockCode, Length: 1385, dtype: object

In [21]:
cats = pd.DataFrame(split_data.tolist(), columns=tokenizer.CATEGORIES)

In [22]:
cats

,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [24]:
token_shares = pd.concat([tokenizer.token_shares, cats], axis=1)

In [25]:
token_shares

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Pepsi Max S/Fr Cola|7920|Cans|Cola|Diet|Carbon...,20725,142486.739565,0.033501,Pepsi Max S/Fr Cola,7920,Cans,Cola,Diet,Carbonated,Colas
1,Pepsi Max S/Fr Cola|2000|Plastic Bottle|Cola|D...,61704,93836.382958,0.022063,Pepsi Max S/Fr Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
2,Diet Coke|7920|Cans|Cola|Diet|Carbonated|Colas,11390,82349.189990,0.019362,Diet Coke,7920,Cans,Cola,Diet,Carbonated,Colas
3,Tesco Dbl Stng NAS Squash|15000|Plastic Bottle...,78033,78086.030010,0.018360,Tesco Dbl Stng NAS Squash,15000,Plastic Bottle,Not Applicable,Diet,Non Carbonated,Squash
4,Coca Cola|7920|Cans|Cola|Regular|Carbonated|Colas,7491,77949.630000,0.018327,Coca Cola,7920,Cans,Cola,Regular,Carbonated,Colas
...,...,...,...,...,...,...,...,...,...,...,...
1380,Pure Life Sprng Mnrl Wtr|1500|Plastic Bottle|N...,306,153.209999,0.000036,Pure Life Sprng Mnrl Wtr,1500,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1381,Old Jamaica Reg|330|Plastic Bottle|Other Fruit...,375,142.469999,0.000033,Old Jamaica Reg,330,Plastic Bottle,Other Fruit,Regular,Carbonated,Flavoured Carbonated
1382,Wait Essntl Sctt Mnrl Wtr|2000|Plastic Bottle|...,278,142.320001,0.000033,Wait Essntl Sctt Mnrl Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1383,Morr Svrs NAS Cola|2000|Plastic Bottle|Cola|Di...,774,131.890001,0.000031,Morr Svrs NAS Cola,2000,Plastic Bottle,Cola,Diet,Carbonated,Colas
1384,Waitrose Sctt M Wtr|2000|Plastic Bottle|Non Fl...,154,93.950003,0.000022,Waitrose Sctt M Wtr,2000,Plastic Bottle,Non Flavoured,Regular,Carbonated,Unflavoured

In [30]:
prods = pd.DataFrame(dset.StockCode, columns=['StockCode']).merge(token_shares, on='StockCode')

In [31]:
prods

,StockCode,Quantity,Spend,share,Brand_First_Name,Pack_Size_ml,Pack_Type,Taste_Flavor_Fruits_Veg,Sugar_vs_Non_Sugar,Still_vs_Sparkling_for_Water,Segment
0,Asda Mineral Water|6000|Plastic Bottle|Non Fla...,5736,9175.130129,0.002157,Asda Mineral Water,6000,Plastic Bottle,Non Flavoured,Regular,Non Carbonated,Unflavoured
1,Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...,1746,1938.290003,0.000456,Rubicon Exotic,1000,Cartons,Tropical/Exotic,Regular,Non Carbonated,Juice Drinks
2,Asda Fruit Juice|1000|Cartons|Orange|Regular|N...,22071,16286.719922,0.003829,Asda Fruit Juice,1000,Cartons,Orange,Regular,Non Carbonated,Pure Juices
3,Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...,8952,2930.450061,0.000689,Asda Lemonade,2000,Plastic Bottle,Lemonade Clear,Regular,Carbonated,Lemonade
4,Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...,8169,3746.890004,0.000881,Asda Zero,2000,Plastic Bottle,Orange,Diet,Carbonated,Flavoured Carbonated
...,...,...,...,...,...,...,...,...,...,...,...
2005211,Copella Pr Jc|1350|Plastic Bottle|Other Multi ...,1405,3255.129998,0.000765,Copella Pr Jc,1350,Plastic Bottle,Other Multi Fruit,Regular,Non Carbonated,Pure Juices
2005212,Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas,498,416.010007,0.000098,Coca Cola,250,Cans,Cola,Regular,Carbonated,Colas
2005213,Copella Pr Jc|900|Plastic Bottle|Apple|Regular...,507,852.599999,0.000200,Copella Pr Jc,900,Plastic Bottle,Apple,Regular,Non Carbonated,Pure Juices
2005214,Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...,2874,3049.619996,0.000717,Rbnsns NAS Frt Shoot,800,Plst Btl with Sports Cap,Other Multi Fruit,Diet,Non Carbonated,Juice Drinks
2005215,Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...,25273,29950.190281,0.007042,Tesco Pr Jc,1000,Plastic Bottle,Orange,Regular,Non Carbonated,Pure Juices

In [39]:
assert (dset.StockCode == prods.StockCode).all()

In [35]:
prods.StockCode

0          Asda Mineral Water|6000|Plastic Bottle|Non Fla...
1          Rubicon Exotic|1000|Cartons|Tropical/Exotic|Re...
2          Asda Fruit Juice|1000|Cartons|Orange|Regular|N...
3          Asda Lemonade|2000|Plastic Bottle|Lemonade Cle...
4          Asda Zero|2000|Plastic Bottle|Orange|Diet|Carb...
                                 ...
2005211    Copella Pr Jc|1350|Plastic Bottle|Other Multi ...
2005212     Coca Cola|250|Cans|Cola|Regular|Carbonated|Colas
2005213    Copella Pr Jc|900|Plastic Bottle|Apple|Regular...
2005214    Rbnsns NAS Frt Shoot|800|Plst Btl with Sports ...
2005215    Tesco Pr Jc|1000|Plastic Bottle|Orange|Regular...
Name: StockCode, Length: 2005216, dtype: object